# リクエスト
sensor_msgs/Image depth_image  # 深度画像を渡す
---
# レスポンス
float64 x
float64 y
float64 z
float64 qx
float64 qy
float64 qz
float64 qw
float64 width     # 平面の幅
float64 height    # 平面の高さ
string drawer_type  # 引き出しの種類（Convex, Concave, SideConvex）
string result     # 結果メッセージ
