(cl:defpackage vgn-srv
  (:use )
  (:export
   "GETMAPCLOUD"
   "<GETMAPCLOUD-REQUEST>"
   "GETMAPCLOUD-REQUEST"
   "<GETMAPCLOUD-RESPONSE>"
   "GETMAPCLOUD-RESPONSE"
   "GETSCENECLOUD"
   "<GETSCENECLOUD-REQUEST>"
   "GETSCENECLOUD-REQUEST"
   "<GETSCENECLOUD-RESPONSE>"
   "GETSCENECLOUD-RESPONSE"
   "PREDICTGRASPS"
   "<PREDICTGRASPS-REQUEST>"
   "PREDICTGRASPS-REQUEST"
   "<PREDICTGRASPS-RESPONSE>"
   "PREDICTGRASPS-RESPONSE"
  ))

