// Generated by gencpp from file vgn/GetMapCloud.msg
// DO NOT EDIT!


#ifndef VGN_MESSAGE_GETMAPCLOUD_H
#define VGN_MESSAGE_GETMAPCLOUD_H

#include <ros/service_traits.h>


#include <vgn/GetMapCloudRequest.h>
#include <vgn/GetMapCloudResponse.h>


namespace vgn
{

struct GetMapCloud
{

typedef GetMapCloudRequest Request;
typedef GetMapCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMapCloud
} // namespace vgn


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vgn::GetMapCloud > {
  static const char* value()
  {
    return "40b2d5c19b1ba0f3eae539bbfbf252ac";
  }

  static const char* value(const ::vgn::GetMapCloud&) { return value(); }
};

template<>
struct DataType< ::vgn::GetMapCloud > {
  static const char* value()
  {
    return "vgn/GetMapCloud";
  }

  static const char* value(const ::vgn::GetMapCloud&) { return value(); }
};


// service_traits::MD5Sum< ::vgn::GetMapCloudRequest> should match
// service_traits::MD5Sum< ::vgn::GetMapCloud >
template<>
struct MD5Sum< ::vgn::GetMapCloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vgn::GetMapCloud >::value();
  }
  static const char* value(const ::vgn::GetMapCloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vgn::GetMapCloudRequest> should match
// service_traits::DataType< ::vgn::GetMapCloud >
template<>
struct DataType< ::vgn::GetMapCloudRequest>
{
  static const char* value()
  {
    return DataType< ::vgn::GetMapCloud >::value();
  }
  static const char* value(const ::vgn::GetMapCloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vgn::GetMapCloudResponse> should match
// service_traits::MD5Sum< ::vgn::GetMapCloud >
template<>
struct MD5Sum< ::vgn::GetMapCloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vgn::GetMapCloud >::value();
  }
  static const char* value(const ::vgn::GetMapCloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vgn::GetMapCloudResponse> should match
// service_traits::DataType< ::vgn::GetMapCloud >
template<>
struct DataType< ::vgn::GetMapCloudResponse>
{
  static const char* value()
  {
    return DataType< ::vgn::GetMapCloud >::value();
  }
  static const char* value(const ::vgn::GetMapCloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VGN_MESSAGE_GETMAPCLOUD_H
