// Generated by gencpp from file vgn/GetSceneCloud.msg
// DO NOT EDIT!


#ifndef VGN_MESSAGE_GETSCENECLOUD_H
#define VGN_MESSAGE_GETSCENECLOUD_H

#include <ros/service_traits.h>


#include <vgn/GetSceneCloudRequest.h>
#include <vgn/GetSceneCloudResponse.h>


namespace vgn
{

struct GetSceneCloud
{

typedef GetSceneCloudRequest Request;
typedef GetSceneCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSceneCloud
} // namespace vgn


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vgn::GetSceneCloud > {
  static const char* value()
  {
    return "c698231a2452033f0ed17ae0a4ebd981";
  }

  static const char* value(const ::vgn::GetSceneCloud&) { return value(); }
};

template<>
struct DataType< ::vgn::GetSceneCloud > {
  static const char* value()
  {
    return "vgn/GetSceneCloud";
  }

  static const char* value(const ::vgn::GetSceneCloud&) { return value(); }
};


// service_traits::MD5Sum< ::vgn::GetSceneCloudRequest> should match
// service_traits::MD5Sum< ::vgn::GetSceneCloud >
template<>
struct MD5Sum< ::vgn::GetSceneCloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vgn::GetSceneCloud >::value();
  }
  static const char* value(const ::vgn::GetSceneCloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vgn::GetSceneCloudRequest> should match
// service_traits::DataType< ::vgn::GetSceneCloud >
template<>
struct DataType< ::vgn::GetSceneCloudRequest>
{
  static const char* value()
  {
    return DataType< ::vgn::GetSceneCloud >::value();
  }
  static const char* value(const ::vgn::GetSceneCloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vgn::GetSceneCloudResponse> should match
// service_traits::MD5Sum< ::vgn::GetSceneCloud >
template<>
struct MD5Sum< ::vgn::GetSceneCloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vgn::GetSceneCloud >::value();
  }
  static const char* value(const ::vgn::GetSceneCloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vgn::GetSceneCloudResponse> should match
// service_traits::DataType< ::vgn::GetSceneCloud >
template<>
struct DataType< ::vgn::GetSceneCloudResponse>
{
  static const char* value()
  {
    return DataType< ::vgn::GetSceneCloud >::value();
  }
  static const char* value(const ::vgn::GetSceneCloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VGN_MESSAGE_GETSCENECLOUD_H
