// Generated by gencpp from file vgn/GetSceneCloudRequest.msg
// DO NOT EDIT!


#ifndef VGN_MESSAGE_GETSCENECLOUDREQUEST_H
#define VGN_MESSAGE_GETSCENECLOUDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vgn
{
template <class ContainerAllocator>
struct GetSceneCloudRequest_
{
  typedef GetSceneCloudRequest_<ContainerAllocator> Type;

  GetSceneCloudRequest_()
    {
    }
  GetSceneCloudRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::vgn::GetSceneCloudRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vgn::GetSceneCloudRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSceneCloudRequest_

typedef ::vgn::GetSceneCloudRequest_<std::allocator<void> > GetSceneCloudRequest;

typedef boost::shared_ptr< ::vgn::GetSceneCloudRequest > GetSceneCloudRequestPtr;
typedef boost::shared_ptr< ::vgn::GetSceneCloudRequest const> GetSceneCloudRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vgn::GetSceneCloudRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vgn::GetSceneCloudRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace vgn

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vgn::GetSceneCloudRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vgn::GetSceneCloudRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vgn::GetSceneCloudRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vgn::GetSceneCloudRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vgn::GetSceneCloudRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vgn::GetSceneCloudRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vgn::GetSceneCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::vgn::GetSceneCloudRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::vgn::GetSceneCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vgn/GetSceneCloudRequest";
  }

  static const char* value(const ::vgn::GetSceneCloudRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vgn::GetSceneCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::vgn::GetSceneCloudRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vgn::GetSceneCloudRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSceneCloudRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vgn::GetSceneCloudRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::vgn::GetSceneCloudRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // VGN_MESSAGE_GETSCENECLOUDREQUEST_H
