// Generated by gencpp from file vgn/GraspConfig.msg
// DO NOT EDIT!


#ifndef VGN_MESSAGE_GRASPCONFIG_H
#define VGN_MESSAGE_GRASPCONFIG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace vgn
{
template <class ContainerAllocator>
struct GraspConfig_
{
  typedef GraspConfig_<ContainerAllocator> Type;

  GraspConfig_()
    : pose()
    , width(0.0)
    , quality(0.0)  {
    }
  GraspConfig_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , width(0.0)
    , quality(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef float _width_type;
  _width_type width;

   typedef float _quality_type;
  _quality_type quality;





  typedef boost::shared_ptr< ::vgn::GraspConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vgn::GraspConfig_<ContainerAllocator> const> ConstPtr;

}; // struct GraspConfig_

typedef ::vgn::GraspConfig_<std::allocator<void> > GraspConfig;

typedef boost::shared_ptr< ::vgn::GraspConfig > GraspConfigPtr;
typedef boost::shared_ptr< ::vgn::GraspConfig const> GraspConfigConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vgn::GraspConfig_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vgn::GraspConfig_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vgn::GraspConfig_<ContainerAllocator1> & lhs, const ::vgn::GraspConfig_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.width == rhs.width &&
    lhs.quality == rhs.quality;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vgn::GraspConfig_<ContainerAllocator1> & lhs, const ::vgn::GraspConfig_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vgn

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vgn::GraspConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vgn::GraspConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vgn::GraspConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vgn::GraspConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vgn::GraspConfig_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vgn::GraspConfig_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vgn::GraspConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffb74d75fb92764666a6fb85638db3e0";
  }

  static const char* value(const ::vgn::GraspConfig_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffb74d75fb927646ULL;
  static const uint64_t static_value2 = 0x66a6fb85638db3e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::vgn::GraspConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vgn/GraspConfig";
  }

  static const char* value(const ::vgn::GraspConfig_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vgn::GraspConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"float32 width\n"
"float32 quality\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::vgn::GraspConfig_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vgn::GraspConfig_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.width);
      stream.next(m.quality);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspConfig_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vgn::GraspConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vgn::GraspConfig_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "quality: ";
    Printer<float>::stream(s, indent + "  ", v.quality);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VGN_MESSAGE_GRASPCONFIG_H
