// Generated by gencpp from file vgn/PredictGrasps.msg
// DO NOT EDIT!


#ifndef VGN_MESSAGE_PREDICTGRASPS_H
#define VGN_MESSAGE_PREDICTGRASPS_H

#include <ros/service_traits.h>


#include <vgn/PredictGraspsRequest.h>
#include <vgn/PredictGraspsResponse.h>


namespace vgn
{

struct PredictGrasps
{

typedef PredictGraspsRequest Request;
typedef PredictGraspsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PredictGrasps
} // namespace vgn


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vgn::PredictGrasps > {
  static const char* value()
  {
    return "c81c71905509ce157d8c512e48cd31ad";
  }

  static const char* value(const ::vgn::PredictGrasps&) { return value(); }
};

template<>
struct DataType< ::vgn::PredictGrasps > {
  static const char* value()
  {
    return "vgn/PredictGrasps";
  }

  static const char* value(const ::vgn::PredictGrasps&) { return value(); }
};


// service_traits::MD5Sum< ::vgn::PredictGraspsRequest> should match
// service_traits::MD5Sum< ::vgn::PredictGrasps >
template<>
struct MD5Sum< ::vgn::PredictGraspsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vgn::PredictGrasps >::value();
  }
  static const char* value(const ::vgn::PredictGraspsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vgn::PredictGraspsRequest> should match
// service_traits::DataType< ::vgn::PredictGrasps >
template<>
struct DataType< ::vgn::PredictGraspsRequest>
{
  static const char* value()
  {
    return DataType< ::vgn::PredictGrasps >::value();
  }
  static const char* value(const ::vgn::PredictGraspsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vgn::PredictGraspsResponse> should match
// service_traits::MD5Sum< ::vgn::PredictGrasps >
template<>
struct MD5Sum< ::vgn::PredictGraspsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vgn::PredictGrasps >::value();
  }
  static const char* value(const ::vgn::PredictGraspsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vgn::PredictGraspsResponse> should match
// service_traits::DataType< ::vgn::PredictGrasps >
template<>
struct DataType< ::vgn::PredictGraspsResponse>
{
  static const char* value()
  {
    return DataType< ::vgn::PredictGrasps >::value();
  }
  static const char* value(const ::vgn::PredictGraspsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VGN_MESSAGE_PREDICTGRASPS_H
